apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 3
  dataVolumeCapacity: 10Gi
  image:
    application: confluentinc/cp-server:8.3.0
    init: confluentinc/confluent-init-container:3.3.0
  dependencies:
    kRaftController:
      clusterRef:
        name: kraftcontroller
  podTemplate:
    podSecurityContext: {}
